// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VinylShop.DBContext;

#nullable disable

namespace VinylShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530034730_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VinylShop.Models.Brand", b =>
                {
                    b.Property<int>("id_brand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_brand"));

                    b.Property<string>("country")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_brand");

                    b.ToTable("brands");

                    b.HasData(
                        new
                        {
                            id_brand = 1,
                            country = "Япония",
                            description = "Легендарные вертушки",
                            name = "Technics"
                        },
                        new
                        {
                            id_brand = 2,
                            country = "Япония",
                            description = "Отличный выбор для старта",
                            name = "Audio-Technica"
                        });
                });

            modelBuilder.Entity("VinylShop.Models.Condition", b =>
                {
                    b.Property<int>("id_condition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_condition"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_condition");

                    b.ToTable("conditions");

                    b.HasData(
                        new
                        {
                            id_condition = 1,
                            description = "Абсолютно новая, не проигрывалась, возможно, запечатанная. Конверт и вложения в идеальном состоянии.",
                            name = "Mint (M)"
                        },
                        new
                        {
                            id_condition = 2,
                            description = "Пластинка выглядит как новая, без видимых дефектов, проигрывалась несколько раз. Звук чистый, без посторонних шумов.",
                            name = "Near Mint (NM)"
                        },
                        new
                        {
                            id_condition = 3,
                            description = "Имеются следы использования, мелкие поверхностные царапины, не влияющие на качество звука. Допускается лёгкий треск в паузах.",
                            name = "Excellent (EX)"
                        },
                        new
                        {
                            id_condition = 4,
                            description = "Качество звука заметно ухудшилось. Возможны некоторые искажения, глубокие и длинные царапины. Обложка и вложения пострадали от сгибов, повреждений краёв, разрывов корешка, обесцвечивания и т. п.",
                            name = "Very Good (VG)"
                        },
                        new
                        {
                            id_condition = 5,
                            description = "Ещё можно проигрывать, но с пластинкой обращались неправильно, она имеет заметный шум и даже может «прыгать». Конверт и вложения порваны, испачканы, испорчены.",
                            name = "Fair (F)"
                        });
                });

            modelBuilder.Entity("VinylShop.Models.Delivery", b =>
                {
                    b.Property<int>("id_delivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_delivery"));

                    b.Property<string>("delivery_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id_delivery");

                    b.HasIndex("userId");

                    b.ToTable("deliveries");

                    b.HasData(
                        new
                        {
                            id_delivery = 1,
                            delivery_address = "г. Санкт-Петербург, ул. Большая Морская, д. 18",
                            orderDate = new DateTime(2026, 5, 30, 3, 47, 30, 554, DateTimeKind.Utc).AddTicks(1439),
                            status_text = "В пути",
                            userId = 2
                        });
                });

            modelBuilder.Entity("VinylShop.Models.Genre", b =>
                {
                    b.Property<int>("id_genre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_genre"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_genre");

                    b.ToTable("genres");

                    b.HasData(
                        new
                        {
                            id_genre = 1,
                            description = "Classic Rock and Metal",
                            name = "Rock"
                        },
                        new
                        {
                            id_genre = 2,
                            description = "Smooth and Bebop Jazz",
                            name = "Jazz"
                        },
                        new
                        {
                            id_genre = 3,
                            description = "Modern and Synth Pop",
                            name = "Pop"
                        });
                });

            modelBuilder.Entity("VinylShop.Models.Player", b =>
                {
                    b.Property<int>("id_player")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_player"));

                    b.Property<int>("brandId")
                        .HasColumnType("integer");

                    b.Property<int>("driveTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("price")
                        .HasColumnType("numeric");

                    b.HasKey("id_player");

                    b.HasIndex("brandId");

                    b.HasIndex("driveTypeId");

                    b.ToTable("players");

                    b.HasData(
                        new
                        {
                            id_player = 1,
                            brandId = 2,
                            driveTypeId = 1,
                            model = "AT-LP120X",
                            price = 35000m
                        },
                        new
                        {
                            id_player = 2,
                            brandId = 1,
                            driveTypeId = 1,
                            model = "SL-1200",
                            price = 85000m
                        });
                });

            modelBuilder.Entity("VinylShop.Models.Role", b =>
                {
                    b.Property<int>("id_role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_role"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_role");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            id_role = 1,
                            name = "Admin"
                        },
                        new
                        {
                            id_role = 2,
                            name = "User"
                        });
                });

            modelBuilder.Entity("VinylShop.Models.Status", b =>
                {
                    b.Property<int>("id_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_status"));

                    b.Property<int>("discount_percentage")
                        .HasColumnType("integer");

                    b.Property<decimal>("min_spend")
                        .HasColumnType("numeric");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_status");

                    b.ToTable("statuses");

                    b.HasData(
                        new
                        {
                            id_status = 1,
                            discount_percentage = 0,
                            min_spend = 0m,
                            name = "Новичок"
                        },
                        new
                        {
                            id_status = 2,
                            discount_percentage = 3,
                            min_spend = 10000m,
                            name = "Бронзовый"
                        },
                        new
                        {
                            id_status = 3,
                            discount_percentage = 5,
                            min_spend = 30000m,
                            name = "Серебряный"
                        },
                        new
                        {
                            id_status = 4,
                            discount_percentage = 10,
                            min_spend = 70000m,
                            name = "Золотой"
                        },
                        new
                        {
                            id_status = 5,
                            discount_percentage = 15,
                            min_spend = 150000m,
                            name = "Платиновый"
                        });
                });

            modelBuilder.Entity("VinylShop.Models.TypeDrive", b =>
                {
                    b.Property<int>("id_drive_type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_drive_type"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_drive_type");

                    b.ToTable("drive_types");

                    b.HasData(
                        new
                        {
                            id_drive_type = 1,
                            description = "Двигатель вращает диск напрямую",
                            name = "Прямой"
                        },
                        new
                        {
                            id_drive_type = 2,
                            description = "Передача через пассик",
                            name = "Ременной"
                        });
                });

            modelBuilder.Entity("VinylShop.Models.User", b =>
                {
                    b.Property<int>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_user"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("roleId")
                        .HasColumnType("integer");

                    b.Property<int>("statusId")
                        .HasColumnType("integer");

                    b.HasKey("id_user");

                    b.HasIndex("roleId");

                    b.HasIndex("statusId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id_user = 1,
                            email = "admin@vinyl.ru",
                            login = "admin",
                            password = "admin",
                            roleId = 1,
                            statusId = 3
                        },
                        new
                        {
                            id_user = 2,
                            email = "ivan@mail.ru",
                            login = "ivan_vinyl",
                            password = "password123",
                            roleId = 2,
                            statusId = 1
                        });
                });

            modelBuilder.Entity("VinylShop.Models.Vinyl", b =>
                {
                    b.Property<int>("id_vinyl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_vinyl"));

                    b.Property<string>("album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("conditionId")
                        .HasColumnType("integer");

                    b.Property<int>("genreId")
                        .HasColumnType("integer");

                    b.Property<decimal>("price")
                        .HasColumnType("numeric");

                    b.HasKey("id_vinyl");

                    b.HasIndex("conditionId");

                    b.HasIndex("genreId");

                    b.ToTable("vinyls");

                    b.HasData(
                        new
                        {
                            id_vinyl = 1,
                            album = "The Dark Side of the Moon",
                            artist = "Pink Floyd",
                            conditionId = 1,
                            genreId = 1,
                            price = 4500m
                        },
                        new
                        {
                            id_vinyl = 2,
                            album = "Kind of Blue",
                            artist = "Miles Davis",
                            conditionId = 2,
                            genreId = 2,
                            price = 3800m
                        });
                });

            modelBuilder.Entity("VinylShop.Models.Delivery", b =>
                {
                    b.HasOne("VinylShop.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VinylShop.Models.Player", b =>
                {
                    b.HasOne("VinylShop.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VinylShop.Models.TypeDrive", "DriveType")
                        .WithMany()
                        .HasForeignKey("driveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("DriveType");
                });

            modelBuilder.Entity("VinylShop.Models.User", b =>
                {
                    b.HasOne("VinylShop.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VinylShop.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("statusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("VinylShop.Models.Vinyl", b =>
                {
                    b.HasOne("VinylShop.Models.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("conditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VinylShop.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("genreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
